-- 1. Creacion de Clientes
INSERT INTO PERSONA (DIRECCION, EDAD, GENERO, IDENTIFICACION, NOMBRE, TELEFONO) VALUES ('Otavalo sn y principal', 18, 0, 'ID1111', 'Jose Lema', '098254785');
INSERT INTO PERSONA (DIRECCION, EDAD, GENERO, IDENTIFICACION, NOMBRE, TELEFONO) VALUES ('Amazonas y NNUU', 18, 1, 'ID1112', 'Marianela Montalvo', '09745865');
INSERT INTO PERSONA (DIRECCION, EDAD, GENERO, IDENTIFICACION, NOMBRE, TELEFONO) VALUES ('13 junio y Equinoccial', 18, 0, 'ID1113', 'Juan Osorio', '098874587');

INSERT INTO CLIENTE (CONTRASENA, ESTADO, PERSONA_ID) VALUES ('1234', TRUE, SELECT PERSONA_ID FROM PERSONA WHERE IDENTIFICACION like 'ID1111');
INSERT INTO CLIENTE (CONTRASENA, ESTADO, PERSONA_ID) VALUES ('5678', TRUE, SELECT PERSONA_ID FROM PERSONA WHERE IDENTIFICACION = 'ID1112');
INSERT INTO CLIENTE (CONTRASENA, ESTADO, PERSONA_ID) VALUES ('1245', TRUE, SELECT PERSONA_ID FROM PERSONA WHERE IDENTIFICACION = 'ID1113');

-- 2. Creacion de Cuentas
INSERT INTO CUENTA (ESTADO, NUMERO_CUENTA, SALDO, TIPO_CUENTA, PERSONA_ID) VALUES (TRUE, 478758, 2000.0, 0, SELECT PERSONA_ID FROM PERSONA WHERE NOMBRE LIKE 'Jose Lema');
INSERT INTO CUENTA (ESTADO, NUMERO_CUENTA, SALDO, TIPO_CUENTA, PERSONA_ID) VALUES (TRUE, 225487, 100.0, 1, SELECT PERSONA_ID FROM PERSONA WHERE NOMBRE LIKE 'Marianela Montalvo');
INSERT INTO CUENTA (ESTADO, NUMERO_CUENTA, SALDO, TIPO_CUENTA, PERSONA_ID) VALUES (TRUE, 495878, 0.0, 0, SELECT PERSONA_ID FROM PERSONA WHERE NOMBRE LIKE 'Juan Osorio');
INSERT INTO CUENTA (ESTADO, NUMERO_CUENTA, SALDO, TIPO_CUENTA, PERSONA_ID) VALUES (TRUE, 496825, 540.0, 0, SELECT PERSONA_ID FROM PERSONA WHERE NOMBRE LIKE 'Marianela Montalvo');

-- 3. Creacion de una nueva Cuenta Corriente para Jose Lema
INSERT INTO CUENTA (ESTADO, NUMERO_CUENTA, SALDO, TIPO_CUENTA, PERSONA_ID) VALUES (TRUE, 585545, 1000.0, 1, SELECT PERSONA_ID FROM PERSONA WHERE NOMBRE LIKE 'Jose Lema');

-- Informo a la base de datos que las horas van a estar en GMT
SET TIME ZONE 'GMT';

-- 4. Movimientos
INSERT INTO MOVIMIENTO (FECHA, SALDO_INICIAL, TIPO_MOVIMIENTO, VALOR, CUENTA_ID) VALUES ( '2022-12-28 23.59.59',  2000.0, 0, 575.0, SELECT CUENTA_ID FROM CUENTA WHERE NUMERO_CUENTA = 478758);
INSERT INTO MOVIMIENTO (FECHA, SALDO_INICIAL, TIPO_MOVIMIENTO, VALOR, CUENTA_ID) VALUES ( '2022-12-29 23.59.59',  100.0, 1, 600.0, SELECT CUENTA_ID FROM CUENTA WHERE NUMERO_CUENTA = 225487);
INSERT INTO MOVIMIENTO (FECHA, SALDO_INICIAL, TIPO_MOVIMIENTO, VALOR, CUENTA_ID) VALUES ( '2022-12-30 23.59.59',  0.0, 1, 120.0, SELECT CUENTA_ID FROM CUENTA WHERE NUMERO_CUENTA = 478758);
INSERT INTO MOVIMIENTO (FECHA, SALDO_INICIAL, TIPO_MOVIMIENTO, VALOR, CUENTA_ID) VALUES ( '2022-12-31 23.59.59',  540.0, 0, 540.0, SELECT CUENTA_ID FROM CUENTA WHERE NUMERO_CUENTA = 496825);